Handling error in api_get_package_by_tag(). tags: british transport, limit: 5
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckanext-rasa/ckanext/rasa/data_bot/main/main.py", line 94, in api_get_package_by_tag
    data = api_get_data(HOSTNAME + action)
  File "/usr/lib/ckan/default/src/ckanext-rasa/ckanext/rasa/data_bot/main/main.py", line 86, in api_get_data
    return json.loads(read)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Handling error in api_get_package_by_tag(). tags: british transport, limit: 5
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckanext-rasa/ckanext/rasa/data_bot/main/main.py", line 94, in api_get_package_by_tag
    data = api_get_data(HOSTNAME + action)
  File "/usr/lib/ckan/default/src/ckanext-rasa/ckanext/rasa/data_bot/main/main.py", line 86, in api_get_data
    return json.loads(read)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
